version: '3.8'

services:
  airflow-webserver:
    image: airfsca 
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      # Updated SQL Alchemy connection string to point to local PostgreSQL
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:password@host.docker.internal:5432/Scala
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.basic_auth"
      AIRFLOW_WWW_USER_USERNAME: user
      AIRFLOW_WWW_USER_PASSWORD: password
    volumes:
      - ./airflow:/opt/airflow
      - /d/ScalaAirflowPro:/mnt/scalaairflowpro
      - /c/Users/vanha/spark-3.5.3-bin-hadoop3:/opt/spark 
      
    networks:
      - airflow_network
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: airfsca
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      # Updated SQL Alchemy connection string to point to local PostgreSQL
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:password@host.docker.internal:5432/Scala
    volumes:
      - ./airflow:/opt/airflow
      - /d/ScalaAirflowPro:/mnt/scalaairflowpro
      - /c/Users/vanha/spark-3.5.3-bin-hadoop3:/opt/spark 
    networks:
      - airflow_network
    command: scheduler

networks:
  airflow_network:
    driver: bridge


